### ISSUE TITLE
Weapon Mechanics

### ISSUE THREAD

**Issue by CajoAlbuquerque** [bernas670/xtravaganza#15]
Develop a switching method for weapons, considering the player has already 2 weapons.  
Implement a reloading system

**Comment by BernardoCMoreira** [comment]
- [x]  Allow Switching weapons mode.
- [x]  Allow picking weapons from the ground.
- [x]  Reduce bullets while shooting.
- [x]  Gun reload.
- [x]  Add flash and particles.
