### ISSUE TITLE
Alien and shooting sounds

### ISSUE THREAD

**Issue by CajoAlbuquerque** [bernas670/xtravaganza#40]
Implement sounds for:
- Alien footsteps ✔️ 
- Alien voice
- Gun shooting ✔️ 
- Gun pick/drop ✔️

**Comment by CajoAlbuquerque** [comment]
Note: Make the drop sound play only once at a time

**Comment by bernas670** [comment]
What about the weapon hitting the ground? Should it make a sound as well?
